
# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="testando.mp3"
Content-Type: audio/mpeg

< ./testando.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--



###



# @name create-transcription

POST http://localhost:3333/videos/25408c39-99db-4024-9c3c-28ef6c5fc03d/transcription
Content-Type: application/json

{
    "prompt": "cidadao de bem, Podcast"
}


###

# @name generateai

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "25408c39-99db-4024-9c3c-28ef6c5fc03d",
    "temperature":0.5,
    "template": "Resumo feito da transcrição do video selecionado e cadastrado a seguir: '''{transcription}'''"

}





















